buildscript {
  repositories {
    mavenCentral()
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
}

plugins {
  id 'java'
  id 'maven-publish'
  id 'eclipse'
}

ext.concourseVersion = '0.10.5'

dependencies {
  implementation group: 'com.cinchapi', name: 'accent4j', version: '1.12.0', changing:true
  implementation group: 'com.cinchapi', name: 'concourse-driver-java', version: concourseVersion, changing:true // needed for util classes...
  implementation group: 'com.google.code.findbugs', name: 'jsr305', version:'2.0.1'
  implementation group: 'com.google.guava', name:'guava', version:'25.1-jre'

  testImplementation 'junit:junit:4.11'
}

ext.generateSourcesJar = true
ext.generateTestJar = true
ext.generateJavadocJar = true

repositories {
  mavenCentral()
  maven {
    url 'https://oss.sonatype.org/content/repositories/snapshots/'
  }
  maven {
      url "https://packages.cinchapi.com/public/open-source/maven/"
  }
  maven {
      url "https://packages.cinchapi.com/public/open-source-snapshots/maven/"
  }
  maven {
      url "https://packages.cinchapi.com/public/platform/maven/"
  }
  maven {
      url "https://packages.cinchapi.com/public/platform-snapshots/maven/"
  }
  maven {
    url "https://packages.cinchapi.com/public/enterprise/maven/"
    credentials {
      username = System.getenv('CLOUDSMITH_API_USER')
      password = System.getenv('CLOUDSMITH_API_KEY')
    }
  }
  maven {
    url "https://packages.cinchapi.com/public/enterprise-snapshots/maven/"
    credentials {
      username = System.getenv('CLOUDSMITH_API_USER')
      password = System.getenv('CLOUDSMITH_API_KEY')
    }
  }
}

// Ensure that these transitive dependencies are excluded so we don't get version clashes
def exclusions = [[group : 'com.google.guava', module: 'guava']]
exclusions.each { exclusion ->
  configurations.implementation.dependencies.all {
    if (name != exclusion.module || group != exclusion.group) {
      exclude group: exclusion.group, module: exclusion.module
    }
  }
}

group = 'com.cinchapi'

// The project version is controlled externally by the "version.sh" script.
def getVersion = { ->
  def stdout = new ByteArrayOutputStream()
  exec {
    commandLine 'bash', 'version.sh'
    standardOutput = stdout
  }
  return stdout.toString().trim()
}
version = getVersion()

// Drop the build component from version number and use that for
// publishing
ext.mavenVersion = version.split('\\.')
ext.mavenVersion[3] = ext.mavenVersion[3].replaceAll("[0-9]+-", "-")
ext.mavenVersion[3] = ext.mavenVersion[3].replaceAll("[0-9]+", "").trim()
ext.mavenVersion = ext.mavenVersion.join(".").replace(".-", "-").replaceAll('\\.$', "")

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

if (JavaVersion.current().isJava8Compatible()) {
  allprojects {
    tasks.withType(Javadoc) {
        options.addStringOption('Xdoclint:none', '-quiet')
    }
  }
}

test {
  useJUnit()
  testLogging {
    showStandardStreams = true
  }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

wrapper {
  gradleVersion = '8.14.3'
  distributionType = Wrapper.DistributionType.ALL
}

jar {
  manifest {
    attributes("Specificiation-Title": project.name, "Specificiation-Version": version, "Implementation-Version": version)
  }
}

task javadocJar(type: Jar, dependsOn: javadoc) {
  archiveClassifier = 'javadoc'
  from javadoc.destinationDir
  onlyIf { generateJavadocJar }
}

task sourcesJar(type: Jar, dependsOn: classes) {
  archiveClassifier = 'sources'
  from sourceSets.main.allSource
  onlyIf { generateSourcesJar }
}

task testJar(type: Jar, dependsOn: classes) {
  archiveClassifier = 'tests'
  from sourceSets.test.output
  onlyIf { generateTestJar }
}

artifacts {
  if (generateSourcesJar) {
    archives sourcesJar
  }
  if (generateTestJar) {
    archives testJar
  }
  if (generateJavadocJar) {
    archives javadocJar
  }
}

publishing {
  repositories {
    maven {
      name = 'cloudsmith'
      def releasesRepoUrl = "https://api-g.cloudsmith.io/maven/cinchapi/platform/"
      def snapshotsRepoUrl = "https://api-g.cloudsmith.io/maven/cinchapi/platform-snapshots/"
      url = mavenVersion.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
      credentials {
        username = System.getenv('CLOUDSMITH_API_USER')
        password = System.getenv('CLOUDSMITH_API_KEY')
      }
    }
  }
  publications {
    maven(MavenPublication) {
      from components.java
      artifact sourcesJar
      artifact javadocJar
      artifact testJar
      groupId group
      artifactId project.name
      version mavenVersion
    }
  }
}

